version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - dupl
    - err113
    - errcheck
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godoclint
    - godox
    - gosec
    - govet
    - iface
    - intrange
    - makezero
    - mirror
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - wrapcheck

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    iface:
      enable:
        - identical # Identifies interfaces in the same package that have identical method sets.
        - unused # Identifies interfaces that are not used anywhere in the same package where the interface is defined.
        - opaque # Identifies functions that return interfaces, but the actual returned value is always a single concrete implementation.

    tagliatelle:
      case:
        rules:
          json: camel

  exclusions:
    paths:
      - demo-app

    rules:
      - path: "(scheduler|internal|session|auth|application|doc)/*"
        linters:
          - revive

      - path: log/.*\.go
        text: "var-naming: avoid package names that conflict with Go standard library package names"
        linters:
          - revive

      - path: _test\.go
        linters:
          - dupl
          - err113
          - errcheck
          - goconst
          - gosec
          - nilnil

      - path: database_test\.go
        linters:
          - paralleltest
          - tparallel

formatters:
  enable:
    - gofmt
